name: Daily build of Maven images

on:
  schedule:
    # Runs "at 04:55PM"
    - cron: '55 4 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Trigger Daily Java/Maven Update
    runs-on: [self-hosted]
    steps: 
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}        
      - name: Build and push
        run: ./build-and-push.sh
