name: Daily build of Maven images

on:
  schedule:
    # Runs "at 04:55PM"
    - cron: '55 4 * * *'
  workflow_dispatch:
  push: 
      
jobs:
  build:
    name: build-push-updaterepo
    uses: ebpro/gh-actions-shared-docker/.github/workflows/ci-shareable-docker-qemu.yml@develop
    secrets: inherit
      
