name: Daily builb of Maven images

on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '55 * * * *'

jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: [self-hosted]
    steps: 
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}        
      - name: Build and push
        run: ./build-and-push.sh