#!/usr/bin/with-contenv bash
PUID=${PUID:-1000}
PGID=${PGID:-1000}

groupmod -o -g "$PGID" user
usermod -o -u "$PUID" user

echo -e "\e[93m**** Running as UID:$(id -u user) GID:$(id -g user)  ****\e[38;5;241m"

